//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xsis.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NgxsisDBEntities : DbContext
    {
        public NgxsisDBEntities()
            : base("name=NgxsisDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<x_addrbook> x_addrbook { get; set; }
        public virtual DbSet<x_address> x_address { get; set; }
        public virtual DbSet<x_biodata> x_biodata { get; set; }
        public virtual DbSet<x_biodata_attachment> x_biodata_attachment { get; set; }
        public virtual DbSet<x_catatan> x_catatan { get; set; }
        public virtual DbSet<x_company> x_company { get; set; }
        public virtual DbSet<x_educational_level> x_educational_level { get; set; }
        public virtual DbSet<x_family_relation> x_family_relation { get; set; }
        public virtual DbSet<x_family_tree> x_family_tree { get; set; }
        public virtual DbSet<x_identity_type> x_identity_type { get; set; }
        public virtual DbSet<x_keahlian> x_keahlian { get; set; }
        public virtual DbSet<x_keluarga> x_keluarga { get; set; }
        public virtual DbSet<x_keterangan_tambahan> x_keterangan_tambahan { get; set; }
        public virtual DbSet<x_marital_status> x_marital_status { get; set; }
        public virtual DbSet<x_menu_access> x_menu_access { get; set; }
        public virtual DbSet<x_menutree> x_menutree { get; set; }
        public virtual DbSet<x_note_type> x_note_type { get; set; }
        public virtual DbSet<x_online_test> x_online_test { get; set; }
        public virtual DbSet<x_online_test_detail> x_online_test_detail { get; set; }
        public virtual DbSet<x_organisasi> x_organisasi { get; set; }
        public virtual DbSet<x_pe_referensi> x_pe_referensi { get; set; }
        public virtual DbSet<x_religion> x_religion { get; set; }
        public virtual DbSet<x_rencana_jadwal> x_rencana_jadwal { get; set; }
        public virtual DbSet<x_rencana_jadwal_detail> x_rencana_jadwal_detail { get; set; }
        public virtual DbSet<x_riwayat_pekerjaan> x_riwayat_pekerjaan { get; set; }
        public virtual DbSet<x_riwayat_pelatihan> x_riwayat_pelatihan { get; set; }
        public virtual DbSet<x_riwayat_pendidikan> x_riwayat_pendidikan { get; set; }
        public virtual DbSet<x_riwayat_proyek> x_riwayat_proyek { get; set; }
        public virtual DbSet<x_role> x_role { get; set; }
        public virtual DbSet<x_schedule_type> x_schedule_type { get; set; }
        public virtual DbSet<x_sertifikasi> x_sertifikasi { get; set; }
        public virtual DbSet<x_skill_level> x_skill_level { get; set; }
        public virtual DbSet<x_sumber_loker> x_sumber_loker { get; set; }
        public virtual DbSet<x_test_type> x_test_type { get; set; }
        public virtual DbSet<x_time_period> x_time_period { get; set; }
        public virtual DbSet<x_undangan> x_undangan { get; set; }
        public virtual DbSet<x_undangan_detail> x_undangan_detail { get; set; }
        public virtual DbSet<x_userrole> x_userrole { get; set; }
    
        public virtual ObjectResult<SelectOrganisasi_Result> SelectOrganisasi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectOrganisasi_Result>("SelectOrganisasi");
        }
    }
}
