//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xsis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class x_address
    {
        public long address_id { get; set; }
        public long created_by { get; set; }
        public System.DateTime created_on { get; set; }
        public long modified_by { get; set; }
        public System.DateTime modified_on { get; set; }
        public long deleted_by { get; set; }
        public System.DateTime deleted_on { get; set; }
        public bool is_delete { get; set; }
        public string address1 { get; set; }
        public string postalcode1 { get; set; }
        public string rt1 { get; set; }
        public string rw1 { get; set; }
        public string kelurahan1 { get; set; }
        public string kecamatan1 { get; set; }
        public string region1 { get; set; }
        public string address2 { get; set; }
        public string postalcode2 { get; set; }
        public string rt2 { get; set; }
        public string rw2 { get; set; }
        public string kelurahan2 { get; set; }
        public string kecamatan2 { get; set; }
        public string region2 { get; set; }
    }
}
