//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xsis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class x_biodata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public x_biodata()
        {
            this.x_organisasi = new HashSet<x_organisasi>();
        }
    
        public long id { get; set; }
        public long created_by { get; set; }
        public System.DateTime created_on { get; set; }
        public Nullable<long> modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public Nullable<long> deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_on { get; set; }
        public bool is_delete { get; set; }
        public string fullname { get; set; }
        public string nick_name { get; set; }
        public string pob { get; set; }
        public System.DateTime dob { get; set; }
        public bool gender { get; set; }
        public long religion_id { get; set; }
        public Nullable<int> high { get; set; }
        public Nullable<int> weight { get; set; }
        public string nationality { get; set; }
        public string ethnic { get; set; }
        public string hobby { get; set; }
        public long identity_type_id { get; set; }
        public string identity_no { get; set; }
        public string email { get; set; }
        public string phone_number1 { get; set; }
        public string phone_number2 { get; set; }
        public string parent_phone_number { get; set; }
        public string child_sequence { get; set; }
        public string how_many_brothers { get; set; }
        public long marital_status_id { get; set; }
        public Nullable<long> addrbook_id { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> expired_token { get; set; }
        public string mariage_year { get; set; }
        public long company_id { get; set; }
        public Nullable<bool> is_process { get; set; }
        public Nullable<bool> is_complete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<x_organisasi> x_organisasi { get; set; }
    }
}
