//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xsis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class x_keterangan_tambahan
    {
        public long keterangan_tambahan_id { get; set; }
        public long created_by { get; set; }
        public System.DateTime created_on { get; set; }
        public long modified_by { get; set; }
        public System.DateTime modified_on { get; set; }
        public long deleted_by { get; set; }
        public System.DateTime deleted_on { get; set; }
        public bool is_delete { get; set; }
        public long biodata_id { get; set; }
        public string emergency_contact_name { get; set; }
        public string emergency_contact_phone { get; set; }
        public bool is_negotiable { get; set; }
        public string start_working { get; set; }
        public bool is_ready_to_outofdown { get; set; }
        public bool is_apply_other_place { get; set; }
        public string apply_place { get; set; }
        public string selection_phase { get; set; }
        public bool is_ever_badly_sick { get; set; }
        public string disease_name { get; set; }
        public string disease_time { get; set; }
        public string psychotest_needs { get; set; }
        public string psychotest_time { get; set; }
        public string requirements_required { get; set; }
        public string other_notes { get; set; }
    }
}
