//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xsis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class x_menutree
    {
        public long id { get; set; }
        public string title { get; set; }
        public string menu_image_url { get; set; }
        public string menu_icon { get; set; }
        public int menu_order { get; set; }
        public int menu_level { get; set; }
        public Nullable<long> menu_parent { get; set; }
        public string menu_url { get; set; }
        public string menu_type { get; set; }
        public long created_by { get; set; }
        public System.DateTime created_on { get; set; }
        public Nullable<long> modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public Nullable<long> deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_on { get; set; }
        public bool is_delete { get; set; }
    }
}
