//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xsis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class x_sumber_loker
    {
        public long sumber_loker_id { get; set; }
        public long created_by { get; set; }
        public System.DateTime created_on { get; set; }
        public long modified_by { get; set; }
        public System.DateTime modified_on { get; set; }
        public long deleted_by { get; set; }
        public System.DateTime deleted_on { get; set; }
        public bool is_delete { get; set; }
        public long biodata_id { get; set; }
        public string vacancy_source { get; set; }
        public string candidate_type { get; set; }
        public string event_name { get; set; }
        public string career_center_name { get; set; }
        public string referrer_name { get; set; }
        public string referrer_phone { get; set; }
        public string referrer_email { get; set; }
        public string other_source { get; set; }
        public string last_income { get; set; }
        public System.DateTime apply_date { get; set; }
    }
}
